### ISSUE TITLE
Pin changes for Max3100

### ISSUE THREAD

**Issue by Danny6151** [silver-sat/Payload_Board#2]
There are a couple of problems that need to be resolved with the pins.
1. pins 19 and 23 on the RaspberryPiZero are switched.

These issues are with respect to Release 1.0

**Comment by edwardsnj** [comment]
Systems have chosen the replacement pins

H2-12 -> H2->22
H2-14 -> H2->24

**Comment by Danny6151** [comment]
Update:
1. Pins 19 and 23 from RaspberryPiZero to pins 1 and 3 on the max3100(U5) called BCM_11_SCLK and BCM_10_MOSI are switched and need to be fixed
